### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by earthiverse** [earthiverse/Food#7]
Please don't ask to comment inside a git commit description ( @gongal ), haha.
Ask the question on here, or comment on your commit on github afterwards.

**Comment by earthiverse** [comment]
Also, you committed with syntax errors. A lot of them (Photo.java, especially).
It's not hard to compile and run before you commit.

When you commit, you're supposed to commit if you're not breaking anything. Sometimes it's unavoidable, but definitely not in this case.

![Never half-ass two things. Whole-ass one thing.](http://i.imgur.com/ZPqZE.jpg)

Also, your comments were terrible. "Constructor" and "Getter and Setters" are not useful comments. The code is self explanatory for these.

**Comment by solinas** [comment]
Another important note, if you haven't already been doing this, start now

comments at the top of a method start like this:
/**

then, when you hit enter, eclipse will print stuff that looks like  this:

```
/**
 * (write method description here
 *
 * @param arg1 (write the description for the argument)
 * @returns (write what this returns)
*/
```

Obviously fill in what I've put in brackets.

This is important because eclipse will generate beautiful Javadoc for our project with minimal effort.
