### ISSUE TITLE
Parcelable Objects

### ISSUE THREAD

**Issue by earthiverse** [earthiverse/Food#8]
In order to pass around Recipe and Ingredient things, I think we need to have them implementing Parcelable.

@solinas10 , how did you do this in your assignment? I passed indexes of the database, and had the new activities load it... Not the best approach...

I have a potential solution:
Implement Parcelable on the cache, and have recipes and ingredients and other things have IDs that identify them.
So when you click on a list of items, you add the cache parcel to the bundle along with an ID. Then the activity you open will assume the ID will correspond to a recipe if it's a recipe viewer, an ingredient if it's an ingredient viewer, and so forth.... 

Which means cache will also need getRecipeByID and a getIngredientByID functions.

see: http://developer.android.com/reference/android/os/Parcelable.html

**Comment by solinas** [comment]
I used intents and bundles. It's handy because intents are used to travel between activities anyways. Using intents, you pass exactly what you want, whether it's a recipe or an ingredient, and the "child" activity can access whatever you put in there by a key that you define in the parent activity.

http://stackoverflow.com/questions/3848148/sending-information-with-intent-putextra

http://developer.android.com/reference/android/content/Intent.html

You can also use bundles, which implement parcelable, to easily keep track of a collection of information, and then put the bundle into the intent.

This way we don't need an id for anything in the cache, and it can stay as simple as possible.

**Comment by earthiverse** [comment]
You still use a bundle... I'll explain it better in person tomorrow.

And we still need IDs for recipes, because we have to store them in a database of sorts.

**Comment by earthiverse** [comment]
The cache is accessed as such:

```
Cache cache = new Cache();
cache.load(__Context (Usually "this")__);
/* Functions to and from cache */
cache.save(__Context (Usually "this")__);
```

We will pass RECIPE_ID to the recipe viewer, and similar things to the other viewers, and they are responsible for finding the data in the cache, or if needed, the database.
